sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=qgiscommons
  matrix:
  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
before_install:
- docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
- docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
- sleep 10
script:
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
- docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.settings"
notifications:
  slack:
    rooms:
      secure: gZ0L2cnALXTEOE9RW59BjaT0xEdZfIzMjnI+b7HzSFxmJ1FGkBna8lyxpRfLl3xmlMYr0djtqN+ZUqqE2fmCJJXVgQdvWjOxMlJpsPrqF70oIkcAgVqhqndptKLq4rysAYJi7CYPciIkOKMGpmVYk04WjLGEW7WWXWJS2J8fOEbBYoQF4UivEyL8U/VY7J0GQDCwXozIBJ47YhIkP2iDz9YEROucM644xwZIk9G9+95Ceiv++b4F9Zrd5lZZc3Km3+CnF12QWlfG2IKacTSUe7uc2dBYLefNis5Dz18UbIu/FPBb0oijtKDjYXWn8EKWUjvPdzwEf2K0ZPM2U1P8fzGbv7APLkHmky1qyE294c6bXhqfy2AHdsHb4WGLWlEKh8kdl51JWuHjLXcbgzEISrsXyEQRJgLNxKb0SElTw3SHLMJW7fTocKb0zAP9Wbn1yXh7nEpJAEODyjRoaMif8BorImTOqSaRfySGc+yd8aJFWZML9Ib1UqYOx92N4BpuR7V/630RDMOUI6/tYJu8Gx4Vp5h/vgPptQAQyjIzNkT8fIJObULY26BHNe0IA66rsAXyFk6oL29nZd1c+5YM2v/OqWQLqbMbvZYje+8R9KarqjDP0zqSPgnnNGXhkGSTPuKG2Yg6nK42UN1vGZXWpARdsdnwJ4hWuXv3AEQJF2c=
